server:
  port: 8080

spring:
  application:
    name: MainHotel

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}


amadeus:
  aspect:
    timer: false
  api:
    url:
      authorize: https://test.api.amadeus.com/v1/security/oauth2/token
      by:
        city: https://test.api.amadeus.com/v1/reference-data/locations/hotels/by-city
    key: ${AMADEUS_KEY}
    secret: ${AMADEUS_SECRET}

openai:
  api:
    model: gpt-4-turbo
    url: https://api.openai.com/v1/chat/completions
    key: ${OPENAI_KEY}